export const IDS = {
    "4": "4",
    "7": "7",
    "33": "33",
    "99": "99",
    "!@#$%^&*()_+": "ecndpcaalrlp",
    "(())": "empty-nest",
    "*><>": "starfish",
    ",,,": "commata",
    "///": "slashes",
    "05AB1E": "osabie",
    "05AB1E (legacy)": "05ab1e",
    "1L_a": "1l-a",
    "1L_AOI": "1l-aoi",
    "2DFuck": "2dfuck",
    "2L": "2l",
    "2sable": "2sable",
    "3var": "3var",
    ";#+": "shp",
    "><>": "fish",
    "???": "qqq",
    "A Pear Tree": "a-pear-tree",
    "a-gram": "a-gram",
    "ABC": "abc",
    "ABC-assembler": "abc-assembler",
    "Acc!!": "accbb",
    "Aceto": "aceto",
    "Actually": "actually",
    "Ada (GNAT)": "ada-gnat",
    "Adapt": "adapt",
    "Add++": "addpp",
    "ADJUST": "adjust",
    "Agda": "agda",
    "Agony": "agony",
    "Ahead": "ahead",
    "Aheui (esotope)": "aheui",
    "Alchemist": "alchemist",
    "ALGOL 68 (Genie)": "algol68g",
    "Alice": "alice",
    "Alice & Bob": "alice-bob",
    "Alice ML": "aliceml",
    "AlphaBeta": "alphabeta",
    "Alphabetti spaghetti": "alphabetti-spaghetti",
    "Alphuck": "alphuck",
    "Alumin": "alumin",
    "Ante": "ante",
    "anyfix": "anyfix",
    "APL (Dyalog Classic)": "apl-dyalog-classic",
    "APL (Dyalog Extended)": "apl-dyalog-extended",
    "APL (Dyalog Unicode)": "apl-dyalog",
    "APL (dzaima/APL)": "apl-dzaima",
    "APL (ngn/apl)": "apl-ngn",
    "Appleseed": "appleseed",
    "ARBLE": "arble",
    "Archway": "archway",
    "Archway2": "archway2",
    "Arcyóu": "arcyou",
    "ArnoldC": "arnoldc",
    "AsciiDots": "asciidots",
    "ASPeRiX": "asperix",
    "Assembly (as, x64, Linux)": "assembly-as",
    "Assembly (fasm, x64, Linux)": "assembly-fasm",
    "Assembly (gcc, x64, Linux)": "assembly-gcc",
    "Assembly (JWasm, x64, Linux)": "assembly-jwasm",
    "Assembly (MIPS, SPIM)": "spim",
    "Assembly (nasm, x64, Linux)": "assembly-nasm",
    "ATS2": "ats2",
    "Attache": "attache",
    "Aubergine": "aubergine",
    "AWK": "awk",
    "axo": "axo",
    "B (ybc)": "ybc",
    "Backhand": "backhand",
    "Bash": "bash",
    "bc": "bc",
    "Beam": "beam",
    "Bean": "bean",
    "BeanShell": "beanshell",
    "Beatnik": "beatnik",
    "Beeswax": "beeswax",
    "Befunge-93": "befunge",
    "Befunge-93 (FBBI)": "befunge-93-fbbi",
    "Befunge-93 (MTFI)": "befunge-93-mtfi",
    "Befunge-93 (PyFunge)": "befunge-93-pyfunge",
    "Befunge-96 (MTFI)": "befunge-96-mtfi",
    "Befunge-97 (MTFI)": "befunge-97-mtfi",
    "Befunge-98 (FBBI)": "befunge-98",
    "Befunge-98 (PyFunge)": "befunge-98-pyfunge",
    "Binary Lambda Calculus": "blc",
    "Bit": "bit",
    "BitBitJump": "bitbitjump",
    "bitch": "bitch",
    "bitch (bit-h)": "bitch-bith",
    "bitch (shifty)": "bitch-shifty",
    "BitChanger": "bitchanger",
    "BitCycle": "bitcycle",
    "Bitwise": "bitwise",
    "Bitwise Cyclic Tag But Way Worse": "bctbww",
    "Bitwise Cyclic Tag But Way Worse 2.0": "bctbww2",
    "Bitwise Fuckery": "bwfuckery",
    "Black (blak)": "blak",
    "Boo": "boo",
    "Boolfuck": "boolfuck",
    "bosh": "bosh",
    "Bot Engine": "bot-engine",
    "Brachylog": "brachylog2",
    "Brachylog v1": "brachylog",
    "Bracmat": "bracmat",
    "Braille": "braille",
    "Brain-Flak": "brain-flak",
    "Brain-Flak (BrainHack)": "brainhack",
    "Brainbash": "brainbash",
    "brainbool": "brainbool",
    "BrainFlump": "brainflump",
    "brainfuck": "brainfuck",
    "Braingolf": "braingolf",
    "Brainlove": "brainlove",
    "BrainSpace": "brainspace",
    "Brat": "brat",
    "Brian & Chuck": "brian-chuck",
    "Broccoli": "broccoli",
    "Bubblegum": "bubblegum",
    "Burlesque": "burlesque",
    "BuzzFizz": "buzzfizz",
    "c": "c-gcc",
    "C (clang)": "c-clang",
    "C (gcc)": "c-gcc",
    "C (tcc)": "c-tcc",
    "C# (.NET Core)": "cs-core",
    "C# (Mono C# compiler)": "cs-mono",
    "C# (Mono C# Shell)": "cs-mono-shell",
    "C# (Visual C# Compiler)": "cs-csc",
    "C# (Visual C# Interactive Compiler)": "cs-csi",
    "C++ (clang)": "cpp-clang",
    "C++ (gcc)": "cpp-gcc",
    "Caboose": "caboose",
    "CakeML": "cakeml",
    "calc (TTK)": "calc2",
    "Canvas": "canvas",
    "Cardinal": "cardinal",
    "Carol & Dave": "carol-dave",
    "Carrot": "carrot",
    "Cascade": "cascade",
    "Catholicon": "catholicon",
    "Cauliflower": "cauliflower",
    "Ceres": "ceres",
    "Ceylon": "ceylon",
    "Chain": "chain",
    "Changeling": "changeling",
    "Chapel": "chapel",
    "Charcoal": "charcoal",
    "Charm": "charm",
    "Check": "check",
    "Checked C": "checkedc",
    "Cheddar": "cheddar",
    "Chef": "chef",
    "Chez Scheme": "scheme-chez",
    "CHICKEN Scheme": "scheme-chicken",
    "Chip": "chip",
    "CIL (Mono IL assembler)": "cil-mono",
    "Cinnamon Gum": "cinnamon-gum",
    "cixl": "cixl",
    "CJam": "cjam",
    "Clam": "clam",
    "Clean": "clean",
    "CLIPS": "clips",
    "Clojure": "clojure",
    "COBOL (GNU)": "cobol-gnu",
    "Cobra": "cobra",
    "Coconut": "coconut",
    "CoffeeScript 1": "coffeescript",
    "CoffeeScript 2": "coffeescript2",
    "Commentator": "commentator",
    "Commercial": "commercial",
    "Common Lisp": "clisp",
    "Condit": "condit",
    "Convex": "convex",
    "Cood": "cood",
    "Corea": "corea",
    "COW": "cow",
    "CPY": "cpy",
    "cQuents": "cquents",
    "Crayon": "crayon",
    "Cryptol": "cryptol",
    "Crystal": "crystal",
    "CSL": "csl",
    "Cubically": "cubically",
    "Cubix": "cubix",
    "Curlyfrick": "curlyfrick",
    "Curry (PAKCS)": "curry-pakcs",
    "Curry (Sloth)": "curry-sloth",
    "Cy": "cy",
    "Cyclone": "cyclone",
    "D": "d",
    "D2": "d2",
    "Dafny": "dafny",
    "Dart": "dart",
    "Dash": "dash",
    "dc": "dc",
    "Deadfish~": "deadfish-",
    "Decimal": "decimal",
    "Del|m|t": "delimit",
    "Deorst": "deorst",
    "Detour": "detour",
    "dg": "dg",
    "Dirty": "dirty",
    "DOBELA": "dobela",
    "DOBELA (dobcon)": "dobela-dobcon",
    "Dodos": "dodos",
    "Dreaderef": "dreaderef",
    "Drive-In Window": "drive-in-window",
    "DScript": "dscript",
    "DStack": "dstack",
    "Dyvil": "dyvil",
    "eacal": "eacal",
    "eC": "ec",
    "ecpp + C (gcc)": "ecpp-c",
    "ecpp + C++ (gcc)": "ecpp-cpp",
    "ed": "ed",
    "Egel": "egel",
    "Element": "element",
    "ELF (x86/x64, Linux)": "elf",
    "Elixir": "elixir",
    "ELVM-IR": "elvm-ir",
    "Emacs Lisp": "emacs-lisp",
    "Emmental": "emmental",
    "Emoji": "emoji",
    "Emoji-gramming": "emoji-gramming",
    "Emojicode": "emojicode6",
    "Emojicode 0.5": "emojicode",
    "EmojiCoder": "emojicoder",
    "emotifuck": "emotifuck",
    "Emotinomicon": "emotinomicon",
    "Enlist": "enlist",
    "Erlang (escript)": "erlang-escript",
    "es": "es",
    "ESOPUNK": "esopunk",
    "ETA": "eta",
    "Euphoria 3": "euphoria3",
    "Euphoria 4": "euphoria4",
    "evil": "evil",
    "Explode": "explode",
    "Extended Brainfuck Type I": "extended-brainfuck-type-i",
    "ExtraC": "extrac",
    "F# (.NET Core)": "fs-core",
    "F# (Mono)": "fs-mono",
    "face": "face",
    "Factor": "factor",
    "FALSE": "false",
    "Fantom": "fantom",
    "Farnsworth": "farnsworth",
    "Felix": "felix",
    "FerNANDo": "fernando",
    "FEU": "feu",
    "FIM++": "fimpp",
    "fish": "fish-shell",
    "Fission": "fission",
    "Fission 2": "fission2",
    "Flipbit": "flipbit",
    "Floater": "floater",
    "Flobnar": "flobnar",
    "Foam": "foam",
    "FOCAL-69": "focal",
    "Foo": "foo",
    "Forget": "forget",
    "Forked": "forked",
    "Forte": "forte",
    "Forth (gforth)": "forth-gforth",
    "Fortran (GFortran)": "fortran-gfortran",
    "Fourier": "fourier",
    "FRACTRAN": "fractran",
    "Fueue": "fueue",
    "Funciton": "funciton",
    "Functoid": "functoid",
    "Funky": "funky",
    "Funky 2": "funky2",
    "Fynyl": "fynyl",
    "Gaia": "gaia",
    "Gambit Scheme (gsi)": "scheme-gambit",
    "Gaot++": "gaotpp",
    "GAP": "gap",
    "Gema": "gema",
    "Geo": "geo",
    "Glypho": "glypho",
    "Glypho (shorthand)": "glypho-shorthand",
    "gnuplot": "gnuplot",
    "Go": "go",
    "Gol><>": "golfish",
    "GolfScript": "golfscript",
    "Granule": "granule",
    "Grass": "grass",
    "Grime": "grime",
    "Groovy": "groovy",
    "GS2": "gs2",
    "Guile": "scheme-guile",
    "Gwion": "gwion",
    "HadesLang": "hades",
    "Half-Broken Car in Heavy Traffic": "hbcht",
    "Haskell": "haskell",
    "Haskell 1.2 (Gofer)": "haskell-gofer",
    "Haskell 98 (Hugs)": "haskell-hugs",
    "hASM": "hasm",
    "Haxe": "haxe",
    "Haystack": "haystack",
    "Hexadecimal Stacking Pseudo-Assembly Language": "hspal",
    "Hexagony": "hexagony",
    "Hobbes": "hobbes",
    "Hodor": "hodor",
    "Homespring": "homespring",
    "Huginn": "huginn",
    "Husk": "husk",
    "Hy": "hy",
    "Hyper-Dimensional Brainfuck": "hdbf",
    "I": "i",
    "iag": "iag",
    "Icon": "icon",
    "Idris": "idris",
    "Implicit": "simplestack",
    "Incident": "incident",
    "ink": "ink",
    "INTERCAL": "intercal",
    "Io": "io",
    "J": "j",
    "J-uby": "j-uby",
    "JAEL": "jael",
    "Japt": "japt",
    "Java (JDK)": "java-jdk",
    "Java (OpenJDK 8)": "java-openjdk",
    "JavaScript (Babel Node)": "javascript-babel-node",
    "JavaScript (Node.js)": "javascript-node",
    "JavaScript (SpiderMonkey)": "javascript-spidermonkey",
    "JavaScript (V8)": "javascript-v8",
    "Jelly": "jelly",
    "Jellyfish": "jellyfish",
    "Joy": "joy",
    "jq": "jq",
    "Julia 0.4": "julia",
    "Julia 0.5": "julia5",
    "Julia 0.6": "julia6",
    "Julia 0.7": "julia7",
    "Julia 1.0": "julia1x",
    "Jx": "jx",
    "K (Kona)": "k-kona",
    "K (ngn/k)": "k-ngn",
    "K (oK)": "k-ok",
    "kavod": "kavod",
    "Keg": "keg",
    "Kipple (cipple)": "kipple-cipple",
    "Klein": "klein",
    "Kobeři-C": "koberi-c",
    "Koka": "koka",
    "Kotlin": "kotlin",
    "krrp": "krrp",
    "ksh": "ksh",
    "l33t": "l33t",
    "Labyrinth": "labyrinth",
    "Lean": "lean",
    "Lean Mean Bean Machine": "lmbm",
    "Lily": "lily",
    "Literate Haskell": "haskell-literate",
    "LLVM IR": "llvm",
    "LNUSP": "lnusp",
    "Locksmith": "locksmith",
    "Logicode": "logicode",
    "LOLCODE": "lolcode",
    "Lost": "lost",
    "LOWER": "lower",
    "Lua": "lua",
    "Lua (LuaJIT)": "lua-luajit",
    "Lua (OpenResty)": "lua-openresty",
    "Ly": "ly",
    "M": "m",
    "M4": "m4",
    "MachineCode": "machinecode",
    "Make": "make",
    "Malbolge": "malbolge",
    "Malbolge Unshackled": "malbolge-unshackled",
    "Mamba": "mamba",
    "MarioLANG": "mariolang",
    "Mascarpone": "mascarpone",
    "MathGolf": "mathgolf",
    "Mathics": "mathics",
    "MATL": "matl",
    "Maverick": "maverick",
    "Maxima": "maxima",
    "MaybeLater": "maybelater",
    "Memory GAP": "memory-gap",
    "MiLambda": "milambda",
    "Milky Way": "milky-way",
    "MineFriff": "minefriff",
    "Minimal-2D": "minimal-2d",
    "miniML": "miniml",
    "Minkolang": "minkolang",
    "Mirror": "mirror",
    "Momema": "momema",
    "Monkeys": "monkeys",
    "Moonscript": "moonscript",
    "Moorhens": "moorhens",
    "Mornington Crescent": "mornington-crescent",
    "Mouse-2002": "mouse2002",
    "Mouse-79": "mouse",
    "Mouse-83": "mouse83",
    "MUMPS": "mumps",
    "Muriel": "muriel",
    "MY": "my",
    "MY-BASIC": "my-basic",
    "nameless language": "nameless",
    "Nandy": "nandy",
    "Neim": "neim",
    "Neutrino": "neutrino",
    "Nhohnhehr": "nhohnhehr",
    "Nial": "nial",
    "Nikud": "nikud",
    "Nim": "nim",
    "No": "no",
    "Noether": "noether",
    "NotQuiteThere": "nqt",
    "NTFJ (NTFJC)": "ntfjc",
    "Numberwang": "numberwang",
    "Oasis": "oasis",
    "ObCode": "obcode",
    "Oberon-07": "oberon-07",
    "Object Pascal (FPC)": "object-pascal-fpc",
    "Objective-C (clang)": "objective-c-clang",
    "Objective-C (gcc)": "objective-c-gcc",
    "OCaml": "ocaml",
    "occam-pi": "occam-pi",
    "Octave": "octave",
    "Odin": "odin",
    "Ohm": "ohm",
    "Ohm v2": "ohm2",
    "OML": "oml",
    "oOo CODE": "ooocode",
    "Oration": "oration",
    "ORK": "ork",
    "Orst": "orst",
    "OSH": "osh",
    "P#": "ps-core",
    "Pain-Flak": "pain-flak",
    "Paradoc": "paradoc",
    "Parenthesis Hell": "parenthesis-hell",
    "Parenthetic": "parenthetic",
    "Pari/GP": "pari-gp",
    "Pascal (FPC)": "pascal-fpc",
    "PATH": "path",
    "pbrain": "pbrain",
    "Perl 4": "perl4",
    "Perl 5": "perl5",
    "Perl 5 (cperl)": "perl5-cperl",
    "Perl 6": "perl6",
    "Perl 6 (Niecza)": "perl6-niecza",
    "Phoenix": "phoenix",
    "Phooey": "phooey",
    "PHP": "php",
    "Physica": "physica",
    "PicoLisp": "picolisp",
    "Piet": "piet",
    "Pike": "pike",
    "PILOT (psPILOT)": "pilot-pspilot",
    "PILOT (RPilot)": "pilot-rpilot",
    "PingPong": "pingpong",
    "Pip": "pip",
    "Pixiedust": "pixiedust",
    "pl": "pl",
    "Pony": "pony",
    "Positron": "positron",
    "PostL": "postl",
    "PostScript (xpost)": "postscript-xpost",
    "PowerShell": "powershell",
    "PowerShell Core": "powershell-core",
    "Prelude": "prelude",
    "Premier": "premier",
    "Preproc": "preproc",
    "Prolog (Ciao)": "prolog-ciao",
    "Prolog (SWI)": "prolog-swi",
    "Proton": "proton",
    "Proton 2.0": "proton2",
    "Pure": "pure",
    "PureScript": "purescript",
    "Purple": "purple",
    "Pushy": "pushy",
    "Puzzlang": "puzzlang",
    "Pyke": "pyke",
    "Pylons": "pylons",
    "PynTree": "pyn-tree",
    "Pyon": "pyon",
    "Pyramid Scheme": "pyramid-scheme",
    "Pyret": "pyret",
    "Pyt": "pyt",
    "Pyth": "pyth",
    "Python 1": "python1",
    "Python 2": "python2",
    "Python 2 (Cython)": "python2-cython",
    "Python 2 (IronPython)": "python2-iron",
    "Python 2 (Jython)": "python2-jython",
    "Python 2 (PyPy)": "python2-pypy",
    "Python 3": "python3",
    "Python 3 (Cython)": "python3-cython",
    "Python 3 (PyPy)": "python3-pypy",
    "Python 3 (Stackless)": "python3-stackless",
    "Python 3.8 (pre-release)": "python38pr",
    "py": "python3-cython",
    "Q#": "qs-core",
    "QuadR": "quadr",
    "Quadrefunge-97 (MTFI)": "quadrefunge-97-mtfi",
    "QuadS": "quads",
    "Quarterstaff": "quarterstaff",
    "Quintefunge-97 (MTFI)": "quintefunge-97-mtfi",
    "R": "r",
    "Racket": "racket",
    "RAD": "rad",
    "Rail": "rail",
    "Random Brainfuck": "random-brainfuck",
    "Rapira": "rapira",
    "Re:direction": "re-direction",
    "Reason": "reason",
    "REBOL": "rebol",
    "REBOL 3": "rebol3",
    "Recursiva": "recursiva",
    "Red": "red",
    "Reng": "reng",
    "ReRegex": "reregex",
    "res": "res",
    "ResPlicate": "resplicate",
    "Reticular": "reticular",
    "Retina": "retina1",
    "Retina 0.8.2": "retina",
    "RETURN": "return",
    "Rexx (Regina)": "rexx",
    "Ring": "ring",
    "rk": "rk",
    "Rockstar": "rockstar",
    "ROOP": "roop",
    "Ropy": "ropy",
    "Rotor": "rotor",
    "RProgN": "rprogn",
    "RProgN 2": "rprogn-2",
    "Ruby": "ruby",
    "Runic Enchantments": "runic",
    "Rust": "rust",
    "Rutger": "rutger",
    "Röda": "roda",
    "S.I.L.O.S": "silos",
    "Sad-Flak": "sad-flak",
    "Sakura": "sakura",
    "Scala": "scala",
    "sed": "sed-gnu",
    "sed 4.2.2": "sed",
    "Seed": "seed",
    "Self-modifying Brainfuck": "smbf",
    "Septefunge-97 (MTFI)": "septefunge-97-mtfi",
    "Seriously": "seriously",
    "Sesos": "sesos",
    "Set": "set",
    "Sexefunge-97 (MTFI)": "sexefunge-97-mtfi",
    "sfk": "sfk",
    "Shakespeare Programming Language": "spl",
    "ShapeScript": "shapescript",
    "Shnap": "shnap",
    "shortC": "shortc",
    "Shove": "shove",
    "Shtriped": "shtriped",
    "Sidef": "sidef",
    "Silberjoder": "silberjoder",
    "Simplefunge": "simplefunge",
    "Simplex": "simplex",
    "Simula (cim)": "simula",
    "SISAL": "sisal",
    "Sisi": "sisi",
    "smol": "smol",
    "Snails": "snails",
    "SNOBOL4 (CSNOBOL4)": "snobol4",
    "Snowman": "snowman",
    "SNUSP (Bloated)": "snusp-bloated",
    "SNUSP (Modular)": "snusp",
    "SNUSP (Snuspi)": "snuspi",
    "Somme": "somme",
    "Spaced": "spaced",
    "Spoon": "spoon",
    "SQLite": "sqlite",
    "Squirrel": "squirrel",
    "Stack Cats": "stackcats",
    "Stacked": "stacked",
    "Standard ML (MLton)": "sml-mlton",
    "Starry": "starry",
    "Stax": "stax",
    "Stencil": "stencil",
    "Stones": "stones",
    "str": "str",
    "Straw": "straw",
    "Subskin": "subskin",
    "Sumerian": "sumerian",
    "Super Stack!": "superstack",
    "SuperMarioLang": "supermariolang",
    "Surface": "surface",
    "Swap": "swap",
    "Swift": "swift4",
    "Symbolic Brainfuck": "sbf",
    "Symbolic Python": "symbolic-python",
    "Syms": "syms",
    "TacO": "taco",
    "Tampio (functional)": "tampio",
    "Tampio (imperative)": "tampioi",
    "Tamsin": "tamsin",
    "TapeBagel": "tapebagel",
    "Taxi": "taxi",
    "Tcl": "tcl",
    "tcsh": "tcsh",
    "TemplAt": "templat",
    "Templates Considered Harmful": "templates",
    "The Amnesiac From Minsk": "amnesiac-from-minsk",
    "The Waterfall Model": "waterfall",
    "Thing": "thing",
    "Threead": "threead",
    "Thue": "thue",
    "Thutu": "thutu",
    "Tidy": "tidy",
    "TinCan": "tincan",
    "tinyBF": "tinybf",
    "tinylisp": "tinylisp",
    "Tir": "tir",
    "TIS": "tis",
    "Toi": "toi",
    "TRANSCRIPT": "transcript",
    "Trefunge-97 (MTFI)": "trefunge-97-mtfi",
    "Trefunge-98 (PyFunge)": "trefunge-98-pyfunge",
    "Triangular": "triangular",
    "Triangularity": "triangularity",
    "Trigger": "trigger",
    "Triple Threat": "triple-threat",
    "TrumpScript": "trumpscript",
    "Turing Machine But Way Worse": "tmbww",
    "Turtlèd": "turtled",
    "TypeScript": "typescript",
    "uBASIC": "ubasic",
    "Underload": "underload",
    "Unefunge-97 (MTFI)": "unefunge-97-mtfi",
    "Unefunge-98 (PyFunge)": "unefunge-98-pyfunge",
    "Unicat": "unicat",
    "Unlambda": "unlambda",
    "Uno": "uno",
    "Unreadable": "unreadable",
    "Ursala": "ursala",
    "V (FMota)": "v-fmota",
    "V (vim)": "v",
    "V (vlang.io)": "vlang",
    "Vala": "vala",
    "VAR": "var",
    "Verbosity": "verbosity",
    "Verbosity v2": "verbosity2",
    "Versert": "versert",
    "Visual Basic .NET (.NET Core)": "vb-core",
    "Visual Basic .NET (Mono)": "visual-basic-net-mono",
    "Visual Basic .NET (VBC)": "visual-basic-net-vbc",
    "Vitsy": "vitsy",
    "VSL": "vsl",
    "W.Y.A.L.H.E.I.N.": "wyalhein",
    "WebAssembly (WaWrapper)": "wasm",
    "Whirl": "whirl",
    "Whispers v1": "whispers",
    "Whispers v2": "whispers2",
    "Whitespace": "whitespace",
    "Width": "width",
    "Wierd (John's)": "wierd",
    "Wise": "wise",
    "Woefully": "woefully",
    "Wolfram Language (Mathematica)": "mathematica",
    "Wren": "wren",
    "wsf": "wsf",
    "Wumpus": "wumpus",
    "xEec": "xeec",
    "xeraph": "xeraph",
    "YABALL": "yaball",
    "Yabasic": "yabasic",
    "yash": "yash",
    "yup": "yup",
    "Z3": "z3",
    "Z80Golf": "z80golf",
    "Zephyr": "zephyr",
    "Zig": "zig",
    "zkl": "zkl",
    "Zoidberg": "zoidberg",
    "Zsh": "zsh",
    "µ6": "mu6"
};